#!/bin/sh
hyprctl clients -j | jq -r 'map(.workspace.id) // [] | unique | if length == 0 then [0] else . end | @csv' | awk -v RS= -F, '
{
    print "["
    for (i=1; i<=NF; i++) print "  " $i ","
    print "]"
}'

